### ISSUE TITLE
パッケージマネージャを統一

### ISSUE THREAD

**Issue by Karibash** [praha-inc/about-us#18]
[package-lock.json](https://github.com/praha-inc/about-us/blob/6d37d6ab20d74f25a6dbe71cfd7cd30ac25810d4/package-lock.json)と[pnpm-lock.yaml](https://github.com/praha-inc/about-us/blob/6d37d6ab20d74f25a6dbe71cfd7cd30ac25810d4/pnpm-lock.yaml)が混在している。

[GitHubActionsの動作検証中](https://github.com/praha-inc/about-us/commit/d18f08eec247928b7162944671d35a46d9626e45)に`package.json`が紛れ込んでしまった模様。
今はVercelを使用しているのでpnpmでも問題ないはず?

今後パッケージマネージャが混在してしまわないように、`package.json`に`packageManager`プロパティを追加した方が良さそう。
https://zenn.dev/teppeis/articles/2021-05-corepack#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%A7%E3%81%AE%E5%88%A9%E7%94%A8

**Comment by penpendayo** [comment]
以下で修正済みなので閉じます

- https://github.com/praha-inc/about-us/pull/30
