### ISSUE TITLE
favicon設定

### ISSUE THREAD

**Issue by Karibash** [praha-inc/about-us#19]
faviconの設定が漏れている為、ブラウザのタブ及びブックマーク時にアイコンが表示されていない。
publicディレクトリへfaviconの配置、headタグへの追記が必要。
https://nextra.site/docs/docs-theme/theme-configuration#head-tags

**Comment by penpendayo** [comment]
以下で設定済みなので閉じます

- https://github.com/praha-inc/about-us/pull/55
