### ISSUE TITLE
SEO設定

### ISSUE THREAD

**Issue by Karibash** [praha-inc/about-us#20]
Nextraの初期設定のままになっている為、SEO周りの設定がNextra関連のままになっている。
<img width="485" alt="スクリーンショット 2023-02-10 21 46 15" src="https://user-images.githubusercontent.com/40270352/218096735-c767fa16-1a44-42db-992e-db4d3fa68e40.png">

MarkdownにfrontMatterを追記し、frontMatterをもとにheadタグを書き換えるようにするのが良さそう。
https://nextra.site/docs/docs-theme/theme-configuration#dynamic-tags-based-on-page

**Comment by penpendayo** [comment]
以下などで修正したので閉じます

- https://github.com/praha-inc/about-us/pull/55
- https://github.com/praha-inc/about-us/pull/54
